# JWT
JWT_AUTHORITIES_KEY: ENC(3Qaqo9HNjBlLxpU8vLWlGQ==)
JWT_SECRET_KEY: ENC(5G4MhSXN6xSQfeSy/0azX38QSfPQ1/rcvcUcw/+XYpKa1vU66asNYFU77Ww93rWaNah+jHNY+vhfSkZathmoapeJIp16HhGKRn4MTk+WI7s7UR3GnQNrHF12zLhN12i1ncXbci6Ne+U=)
JWT_ACCESS_TOKEN_EXPIRES_IN: 7200 # 2 * 60 * 60

# DATABASE
# MySQL - prod
MYSQL_URL: ENC(Lxd1JhAS2gRjqKrSbZIpFru9U0Ltmd3yXKXbwDYmlDJ+uJxDwYL17mIu8yB3ynhXlIC9UkGA1ZdL6m9JNdBeQA+sGuCFJFplCnYHmKHkGsw3k+wjiy+3w6TZ4it/DBQwtHWOGLtwpzw=)
MYSQL_USERNAME: ENC(vhCd4j+FsQRLsoSnP1RfzQ==)
MYSQL_PASSWORD: ENC(enE2KwfjMRGa4miB+lVmXK9DjBrpfsLy)
# H2 - dev
H2_URL: ENC(J5x/CvQ0YddqyfMFJA8kjlnL+k7Oyio1sKB3W8569lflklB654Wfdw==)
H2_USERNAME: ENC(FZAeOFUrzKOmG9TDqvBLsA==)
H2_PASSWORD:

# AWS - S3
S3_BUCKET: ENC(odo1EqxFgpHgLh/mo960sRStzwUagQPv6TZfvHUlq1dI4f6yXHEkBg==)
S3_ACCESS_KEY: ENC(EHbLkA8A94EcMQBOjJZnWqlYKccKde63xEHFhwwKiXw=)
S3_SECRET_KEY: ENC(oOQVJ36PHV0JvTFILDskBN5/RwqBjndPJQPaaE6BbgFrioD0OLSF1f+sdlBU2gjva94DclWD6NI=)
S3_STATIC: ap-northeast-2
