# JWT
JWT_AUTHORITIES_KEY: ENC(3Qaqo9HNjBlLxpU8vLWlGQ==)
JWT_SECRET_KEY: ENC(5G4MhSXN6xSQfeSy/0azX38QSfPQ1/rcvcUcw/+XYpKa1vU66asNYFU77Ww93rWaNah+jHNY+vhfSkZathmoapeJIp16HhGKRn4MTk+WI7s7UR3GnQNrHF12zLhN12i1ncXbci6Ne+U=)
JWT_ACCESS_TOKEN_EXPIRES_IN: 7200 # 2 * 60 * 60

# DATABASE
# MySQL - prod
MYSQL_URL: ENC(Lxd1JhAS2gRjqKrSbZIpFru9U0Ltmd3yXKXbwDYmlDJ+uJxDwYL17mIu8yB3ynhXlIC9UkGA1ZdL6m9JNdBeQA+sGuCFJFplCnYHmKHkGsw3k+wjiy+3w6TZ4it/DBQwtHWOGLtwpzw=)
MYSQL_USERNAME: ENC(vhCd4j+FsQRLsoSnP1RfzQ==)
MYSQL_PASSWORD: ENC(enE2KwfjMRGa4miB+lVmXK9DjBrpfsLy)
# H2 - dev
H2_URL: ENC(StGqDEOMZHn+IwiGjnXp63BjpslfYcKq8hNQ4pbw796pKaFCQ7r4+U9/fIKtHaD1AwdZZYkmMS8=)
H2_USERNAME: ENC(FZAeOFUrzKOmG9TDqvBLsA==)
H2_PASSWORD: