server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_URL}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug

jwt:
  authorities-key: ${JWT_AUTHORITIES_KEY}
  secret-key: ${JWT_SECRET_KEY}
  access-token-expires-in: 7200 # 2 * 60 * 60