server:
  port: 8080

spring:
  profiles:
    group:
      dev:
        - env
        - h2
      prod:
        - env
        - mysql
    default: dev

jasypt:
  encryptor:
    bean: jasyptStringEncryptor