server:
  port: 8080

spring:
  profiles:
    group:
      dev:
        - env
        - h2
      prod:
        - env
        - mysql
    default: dev

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_STATIC}
      auto: false
    stack:
      auto: false